#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcps.DivisionDirectory.ExternalData
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Lcps.v2015")]
	public partial class ExternalDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPersonnel(Personnel instance);
    partial void UpdatePersonnel(Personnel instance);
    partial void DeletePersonnel(Personnel instance);
    partial void InsertNWUser(NWUser instance);
    partial void UpdateNWUser(NWUser instance);
    partial void DeleteNWUser(NWUser instance);
    #endregion
		
		public ExternalDataContext() : 
				base(global::Lcps.DivisionDirectory.Properties.Settings.Default._connectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ExternalDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExternalDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExternalDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExternalDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Personnel> Personnels
		{
			get
			{
				return this.GetTable<Personnel>();
			}
		}
		
		public System.Data.Linq.Table<NWUser> NWUsers
		{
			get
			{
				return this.GetTable<NWUser>();
			}
		}
		
		public System.Data.Linq.Table<StaffCandidate> StaffCandidates
		{
			get
			{
				return this.GetTable<StaffCandidate>();
			}
		}
		
		public System.Data.Linq.Table<ADSIUser> ADSIUsers
		{
			get
			{
				return this.GetTable<ADSIUser>();
			}
		}
		
		public System.Data.Linq.Table<LdapStaffCandidate> LdapStaffCandidates
		{
			get
			{
				return this.GetTable<LdapStaffCandidate>();
			}
		}
		
		public System.Data.Linq.Table<StudentCandidate> StudentCandidates
		{
			get
			{
				return this.GetTable<StudentCandidate>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="ExternalData.[Personnel-Not-In-NwUsers]")]
		public ISingleResult<Personnel> GetPersonnelNotInNWUsers()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Personnel>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="ExternalData.[StaffCandidate-Get-No-Asp]")]
		public ISingleResult<StaffCandidate> GetSatffCandidatesWithNoAsp()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<StaffCandidate>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="ExternalData.[Students-No-Asp-Account]")]
		public ISingleResult<StudentCandidate> GetStudentsWithNoAsp()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<StudentCandidate>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="ExternalData.Personnel")]
	public partial class Personnel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _PersonnelKey;
		
		private string _SSN;
		
		private string _Last_Name;
		
		private string _First_Name;
		
		private string _Middle_Name;
		
		private System.Nullable<System.DateTime> _DOB;
		
		private string _Sex;
		
		private string _Location1;
		
		private string _Position;
		
		private string _Assignment;
		
		private string _PartTime;
		
		private bool _Active;
		
		private System.Nullable<System.DateTime> _Employment_Date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPersonnelKeyChanging(System.Guid value);
    partial void OnPersonnelKeyChanged();
    partial void OnSSNChanging(string value);
    partial void OnSSNChanged();
    partial void OnLast_NameChanging(string value);
    partial void OnLast_NameChanged();
    partial void OnFirst_NameChanging(string value);
    partial void OnFirst_NameChanged();
    partial void OnMiddle_NameChanging(string value);
    partial void OnMiddle_NameChanged();
    partial void OnDOBChanging(System.Nullable<System.DateTime> value);
    partial void OnDOBChanged();
    partial void OnSexChanging(string value);
    partial void OnSexChanged();
    partial void OnLocation1Changing(string value);
    partial void OnLocation1Changed();
    partial void OnPositionChanging(string value);
    partial void OnPositionChanged();
    partial void OnAssignmentChanging(string value);
    partial void OnAssignmentChanged();
    partial void OnPartTimeChanging(string value);
    partial void OnPartTimeChanged();
    partial void OnActiveChanging(bool value);
    partial void OnActiveChanged();
    partial void OnEmployment_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnEmployment_DateChanged();
    #endregion
		
		public Personnel()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonnelKey", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid PersonnelKey
		{
			get
			{
				return this._PersonnelKey;
			}
			set
			{
				if ((this._PersonnelKey != value))
				{
					this.OnPersonnelKeyChanging(value);
					this.SendPropertyChanging();
					this._PersonnelKey = value;
					this.SendPropertyChanged("PersonnelKey");
					this.OnPersonnelKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSN", DbType="NVarChar(12)")]
		public string SSN
		{
			get
			{
				return this._SSN;
			}
			set
			{
				if ((this._SSN != value))
				{
					this.OnSSNChanging(value);
					this.SendPropertyChanging();
					this._SSN = value;
					this.SendPropertyChanged("SSN");
					this.OnSSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Last Name]", Storage="_Last_Name", DbType="NVarChar(30)")]
		public string Last_Name
		{
			get
			{
				return this._Last_Name;
			}
			set
			{
				if ((this._Last_Name != value))
				{
					this.OnLast_NameChanging(value);
					this.SendPropertyChanging();
					this._Last_Name = value;
					this.SendPropertyChanged("Last_Name");
					this.OnLast_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[First Name]", Storage="_First_Name", DbType="NVarChar(20)")]
		public string First_Name
		{
			get
			{
				return this._First_Name;
			}
			set
			{
				if ((this._First_Name != value))
				{
					this.OnFirst_NameChanging(value);
					this.SendPropertyChanging();
					this._First_Name = value;
					this.SendPropertyChanged("First_Name");
					this.OnFirst_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Middle Name]", Storage="_Middle_Name", DbType="NVarChar(50)")]
		public string Middle_Name
		{
			get
			{
				return this._Middle_Name;
			}
			set
			{
				if ((this._Middle_Name != value))
				{
					this.OnMiddle_NameChanging(value);
					this.SendPropertyChanging();
					this._Middle_Name = value;
					this.SendPropertyChanged("Middle_Name");
					this.OnMiddle_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="DateTime")]
		public System.Nullable<System.DateTime> DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this.OnDOBChanging(value);
					this.SendPropertyChanging();
					this._DOB = value;
					this.SendPropertyChanged("DOB");
					this.OnDOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="NVarChar(1)")]
		public string Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this.OnSexChanging(value);
					this.SendPropertyChanging();
					this._Sex = value;
					this.SendPropertyChanged("Sex");
					this.OnSexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location1", DbType="NVarChar(20)")]
		public string Location1
		{
			get
			{
				return this._Location1;
			}
			set
			{
				if ((this._Location1 != value))
				{
					this.OnLocation1Changing(value);
					this.SendPropertyChanging();
					this._Location1 = value;
					this.SendPropertyChanged("Location1");
					this.OnLocation1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position", DbType="NVarChar(40)")]
		public string Position
		{
			get
			{
				return this._Position;
			}
			set
			{
				if ((this._Position != value))
				{
					this.OnPositionChanging(value);
					this.SendPropertyChanging();
					this._Position = value;
					this.SendPropertyChanged("Position");
					this.OnPositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Assignment", DbType="NVarChar(60)")]
		public string Assignment
		{
			get
			{
				return this._Assignment;
			}
			set
			{
				if ((this._Assignment != value))
				{
					this.OnAssignmentChanging(value);
					this.SendPropertyChanging();
					this._Assignment = value;
					this.SendPropertyChanged("Assignment");
					this.OnAssignmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PartTime", DbType="NVarChar(1)")]
		public string PartTime
		{
			get
			{
				return this._PartTime;
			}
			set
			{
				if ((this._PartTime != value))
				{
					this.OnPartTimeChanging(value);
					this.SendPropertyChanging();
					this._PartTime = value;
					this.SendPropertyChanged("PartTime");
					this.OnPartTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit NOT NULL")]
		public bool Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Employment Date]", Storage="_Employment_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Employment_Date
		{
			get
			{
				return this._Employment_Date;
			}
			set
			{
				if ((this._Employment_Date != value))
				{
					this.OnEmployment_DateChanging(value);
					this.SendPropertyChanging();
					this._Employment_Date = value;
					this.SendPropertyChanged("Employment_Date");
					this.OnEmployment_DateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="ExternalData.NWUsers")]
	public partial class NWUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _NWUserKey;
		
		private string _SocSecNbrFormatted;
		
		private string _EntityID;
		
		private string _LN;
		
		private string _FN;
		
		private string _MN;
		
		private string _BirthDateStandard;
		
		private string _Gender;
		
		private string _SchPerDir;
		
		private string _EmpType;
		
		private string _JobTitle;
		
		private string _UserNameNW;
		
		private string _EmailLcps;
		
		private string _Password;
		
		private string _Year;
		
		private string _UserStatus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNWUserKeyChanging(System.Guid value);
    partial void OnNWUserKeyChanged();
    partial void OnSocSecNbrFormattedChanging(string value);
    partial void OnSocSecNbrFormattedChanged();
    partial void OnEntityIDChanging(string value);
    partial void OnEntityIDChanged();
    partial void OnLNChanging(string value);
    partial void OnLNChanged();
    partial void OnFNChanging(string value);
    partial void OnFNChanged();
    partial void OnMNChanging(string value);
    partial void OnMNChanged();
    partial void OnBirthDateStandardChanging(string value);
    partial void OnBirthDateStandardChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnSchPerDirChanging(string value);
    partial void OnSchPerDirChanged();
    partial void OnEmpTypeChanging(string value);
    partial void OnEmpTypeChanged();
    partial void OnJobTitleChanging(string value);
    partial void OnJobTitleChanged();
    partial void OnUserNameNWChanging(string value);
    partial void OnUserNameNWChanged();
    partial void OnEmailLcpsChanging(string value);
    partial void OnEmailLcpsChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnYearChanging(string value);
    partial void OnYearChanged();
    partial void OnUserStatusChanging(string value);
    partial void OnUserStatusChanged();
    #endregion
		
		public NWUser()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NWUserKey", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid NWUserKey
		{
			get
			{
				return this._NWUserKey;
			}
			set
			{
				if ((this._NWUserKey != value))
				{
					this.OnNWUserKeyChanging(value);
					this.SendPropertyChanging();
					this._NWUserKey = value;
					this.SendPropertyChanged("NWUserKey");
					this.OnNWUserKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SocSecNbrFormatted", DbType="NVarChar(50)")]
		public string SocSecNbrFormatted
		{
			get
			{
				return this._SocSecNbrFormatted;
			}
			set
			{
				if ((this._SocSecNbrFormatted != value))
				{
					this.OnSocSecNbrFormattedChanging(value);
					this.SendPropertyChanging();
					this._SocSecNbrFormatted = value;
					this.SendPropertyChanged("SocSecNbrFormatted");
					this.OnSocSecNbrFormattedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntityID", DbType="NVarChar(50)")]
		public string EntityID
		{
			get
			{
				return this._EntityID;
			}
			set
			{
				if ((this._EntityID != value))
				{
					this.OnEntityIDChanging(value);
					this.SendPropertyChanging();
					this._EntityID = value;
					this.SendPropertyChanged("EntityID");
					this.OnEntityIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LN", DbType="NVarChar(40)")]
		public string LN
		{
			get
			{
				return this._LN;
			}
			set
			{
				if ((this._LN != value))
				{
					this.OnLNChanging(value);
					this.SendPropertyChanging();
					this._LN = value;
					this.SendPropertyChanged("LN");
					this.OnLNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FN", DbType="NVarChar(20)")]
		public string FN
		{
			get
			{
				return this._FN;
			}
			set
			{
				if ((this._FN != value))
				{
					this.OnFNChanging(value);
					this.SendPropertyChanging();
					this._FN = value;
					this.SendPropertyChanged("FN");
					this.OnFNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MN", DbType="NVarChar(50)")]
		public string MN
		{
			get
			{
				return this._MN;
			}
			set
			{
				if ((this._MN != value))
				{
					this.OnMNChanging(value);
					this.SendPropertyChanging();
					this._MN = value;
					this.SendPropertyChanged("MN");
					this.OnMNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BirthDateStandard", DbType="NVarChar(50)")]
		public string BirthDateStandard
		{
			get
			{
				return this._BirthDateStandard;
			}
			set
			{
				if ((this._BirthDateStandard != value))
				{
					this.OnBirthDateStandardChanging(value);
					this.SendPropertyChanging();
					this._BirthDateStandard = value;
					this.SendPropertyChanged("BirthDateStandard");
					this.OnBirthDateStandardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="NVarChar(1)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SchPerDir", DbType="NVarChar(50)")]
		public string SchPerDir
		{
			get
			{
				return this._SchPerDir;
			}
			set
			{
				if ((this._SchPerDir != value))
				{
					this.OnSchPerDirChanging(value);
					this.SendPropertyChanging();
					this._SchPerDir = value;
					this.SendPropertyChanged("SchPerDir");
					this.OnSchPerDirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpType", DbType="NVarChar(50)")]
		public string EmpType
		{
			get
			{
				return this._EmpType;
			}
			set
			{
				if ((this._EmpType != value))
				{
					this.OnEmpTypeChanging(value);
					this.SendPropertyChanging();
					this._EmpType = value;
					this.SendPropertyChanged("EmpType");
					this.OnEmpTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobTitle", DbType="NVarChar(50)")]
		public string JobTitle
		{
			get
			{
				return this._JobTitle;
			}
			set
			{
				if ((this._JobTitle != value))
				{
					this.OnJobTitleChanging(value);
					this.SendPropertyChanging();
					this._JobTitle = value;
					this.SendPropertyChanged("JobTitle");
					this.OnJobTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserNameNW", DbType="NVarChar(50)")]
		public string UserNameNW
		{
			get
			{
				return this._UserNameNW;
			}
			set
			{
				if ((this._UserNameNW != value))
				{
					this.OnUserNameNWChanging(value);
					this.SendPropertyChanging();
					this._UserNameNW = value;
					this.SendPropertyChanged("UserNameNW");
					this.OnUserNameNWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailLcps", DbType="NVarChar(255)")]
		public string EmailLcps
		{
			get
			{
				return this._EmailLcps;
			}
			set
			{
				if ((this._EmailLcps != value))
				{
					this.OnEmailLcpsChanging(value);
					this.SendPropertyChanging();
					this._EmailLcps = value;
					this.SendPropertyChanged("EmailLcps");
					this.OnEmailLcpsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="NVarChar(4)")]
		public string Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this.OnYearChanging(value);
					this.SendPropertyChanging();
					this._Year = value;
					this.SendPropertyChanged("Year");
					this.OnYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserStatus", DbType="NVarChar(2)")]
		public string UserStatus
		{
			get
			{
				return this._UserStatus;
			}
			set
			{
				if ((this._UserStatus != value))
				{
					this.OnUserStatusChanging(value);
					this.SendPropertyChanging();
					this._UserStatus = value;
					this.SendPropertyChanged("UserStatus");
					this.OnUserStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="ExternalData.StaffCandidate")]
	public partial class StaffCandidate
	{
		
		private long _MembershipScope;
		
		private string _InternalId;
		
		private string _Surname;
		
		private string _GivenName;
		
		private string _MiddleName;
		
		private System.DateTime _DOB;
		
		private string _GenderValue;
		
		private string _Title;
		
		private string _UserName;
		
		private string _Email;
		
		private string _InitialPassword;
		
		public StaffCandidate()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MembershipScope", DbType="BigInt")]
		public long MembershipScope
		{
			get
			{
				return this._MembershipScope;
			}
			set
			{
				if ((this._MembershipScope != value))
				{
					this._MembershipScope = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InternalId", DbType="NVarChar(12)")]
		public string InternalId
		{
			get
			{
				return this._InternalId;
			}
			set
			{
				if ((this._InternalId != value))
				{
					this._InternalId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="NVarChar(30)")]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this._Surname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GivenName", DbType="NVarChar(20)")]
		public string GivenName
		{
			get
			{
				return this._GivenName;
			}
			set
			{
				if ((this._GivenName != value))
				{
					this._GivenName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="NVarChar(50)")]
		public string MiddleName
		{
			get
			{
				return this._MiddleName;
			}
			set
			{
				if ((this._MiddleName != value))
				{
					this._MiddleName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="DateTime")]
		public System.DateTime DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this._DOB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Gender", Storage="_GenderValue", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string GenderValue
		{
			get
			{
				return this._GenderValue;
			}
			set
			{
				if ((this._GenderValue != value))
				{
					this._GenderValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(60)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(255)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InitialPassword", DbType="NVarChar(50)")]
		public string InitialPassword
		{
			get
			{
				return this._InitialPassword;
			}
			set
			{
				if ((this._InitialPassword != value))
				{
					this._InitialPassword = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="[Lcps.Ldap].ADSIUser")]
	public partial class ADSIUser
	{
		
		private string _samAccountName;
		
		private string _displayName;
		
		private string _employeeId;
		
		public ADSIUser()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_samAccountName", DbType="NVarChar(4000)")]
		public string samAccountName
		{
			get
			{
				return this._samAccountName;
			}
			set
			{
				if ((this._samAccountName != value))
				{
					this._samAccountName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_displayName", DbType="NVarChar(4000)")]
		public string displayName
		{
			get
			{
				return this._displayName;
			}
			set
			{
				if ((this._displayName != value))
				{
					this._displayName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employeeId", DbType="NVarChar(4000)")]
		public string employeeId
		{
			get
			{
				return this._employeeId;
			}
			set
			{
				if ((this._employeeId != value))
				{
					this._employeeId = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Ldap.[Ldap-Staff-New]")]
	public partial class LdapStaffCandidate
	{
		
		private string _Id;
		
		private string _InternalId;
		
		private string _Surname;
		
		private string _GivenName;
		
		private string _MiddleName;
		
		private System.DateTime _DOB;
		
		private int _GenderValue;
		
		private long _MembershipScope;
		
		private string _Title;
		
		private string _InitialPassword;
		
		private string _ConfirmPassword;
		
		private string _Email;
		
		private string _UserName;
		
		public LdapStaffCandidate()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InternalId", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string InternalId
		{
			get
			{
				return this._InternalId;
			}
			set
			{
				if ((this._InternalId != value))
				{
					this._InternalId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="NVarChar(75) NOT NULL", CanBeNull=false)]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this._Surname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GivenName", DbType="NVarChar(75) NOT NULL", CanBeNull=false)]
		public string GivenName
		{
			get
			{
				return this._GivenName;
			}
			set
			{
				if ((this._GivenName != value))
				{
					this._GivenName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="NVarChar(75)")]
		public string MiddleName
		{
			get
			{
				return this._MiddleName;
			}
			set
			{
				if ((this._MiddleName != value))
				{
					this._MiddleName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="DateTime NOT NULL")]
		public System.DateTime DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this._DOB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Gender", Storage="_GenderValue", DbType="Int NOT NULL")]
		public int GenderValue
		{
			get
			{
				return this._GenderValue;
			}
			set
			{
				if ((this._GenderValue != value))
				{
					this._GenderValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MembershipScope", DbType="BigInt NOT NULL")]
		public long MembershipScope
		{
			get
			{
				return this._MembershipScope;
			}
			set
			{
				if ((this._MembershipScope != value))
				{
					this._MembershipScope = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InitialPassword", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string InitialPassword
		{
			get
			{
				return this._InitialPassword;
			}
			set
			{
				if ((this._InitialPassword != value))
				{
					this._InitialPassword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConfirmPassword", DbType="NVarChar(256)")]
		public string ConfirmPassword
		{
			get
			{
				return this._ConfirmPassword;
			}
			set
			{
				if ((this._ConfirmPassword != value))
				{
					this._ConfirmPassword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(256)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="ExternalData.StudentCandidate")]
	public partial class StudentCandidate
	{
		
		private long _MembershipScope;
		
		private string _InternalId;
		
		private string _Surname;
		
		private string _GivenName;
		
		private string _MiddleName;
		
		private string _GenderValue;
		
		private System.DateTime _DOB;
		
		private string _UserName;
		
		private string _Email;
		
		private string _InitialPassword;
		
		private string _Title;
		
		public StudentCandidate()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MembershipScope", DbType="BigInt")]
		public long MembershipScope
		{
			get
			{
				return this._MembershipScope;
			}
			set
			{
				if ((this._MembershipScope != value))
				{
					this._MembershipScope = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InternalId", DbType="NVarChar(50)", CanBeNull=false)]
		public string InternalId
		{
			get
			{
				return this._InternalId;
			}
			set
			{
				if ((this._InternalId != value))
				{
					this._InternalId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="NVarChar(40)", CanBeNull=false)]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this._Surname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GivenName", DbType="NVarChar(20)", CanBeNull=false)]
		public string GivenName
		{
			get
			{
				return this._GivenName;
			}
			set
			{
				if ((this._GivenName != value))
				{
					this._GivenName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="NVarChar(50)")]
		public string MiddleName
		{
			get
			{
				return this._MiddleName;
			}
			set
			{
				if ((this._MiddleName != value))
				{
					this._MiddleName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Gender", Storage="_GenderValue", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string GenderValue
		{
			get
			{
				return this._GenderValue;
			}
			set
			{
				if ((this._GenderValue != value))
				{
					this._GenderValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="datetime")]
		public System.DateTime DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this._DOB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50)", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(255)", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InitialPassword", DbType="NVarChar(50)", CanBeNull=false)]
		public string InitialPassword
		{
			get
			{
				return this._InitialPassword;
			}
			set
			{
				if ((this._InitialPassword != value))
				{
					this._InitialPassword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(50)", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
